[package]
name = "commander"
version = "0.1.0"
authors = ["Ivan Pirlik <abmajor7@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
dirs = "1.0.4"
failure = "0.1.5"
flate2 = "1.0"
log = "0.4"
pulldown-cmark = "0.2.0"
reqwest = "0.9.9"
serde_derive = "1.0"
skim = "0.5.2"
tar = "0.4"
